from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus import HRFlowable
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.lib.styles import (
    getSampleStyleSheet,
)
import os
import re
def clean_filename(value):
    return re.sub(r'[<>:"/\\|?*]', '', value)
os.makedirs(
    "backend/pdfs",
    exist_ok=True,
)


from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.units import mm
def separator():

    return HRFlowable(
        width="100%",
        thickness=1,
    )
def add_footer(
    canvas,
    doc,
):

    canvas.drawString(
        50,
        30,
        "Generated by TravelSync AI",
    )
def add_page_number(canvas, doc):

    page_num = canvas.getPageNumber()

    canvas.drawRightString(
        200 * mm,
        10 * mm,
        f"Page {page_num}",
    )

def generate_pdf(trip):
    source = trip["source"].split(",")[0].strip()
    destination = trip["destination"].split(",")[0].strip()

    filename = (
        f"backend/pdfs/"
        f"{source} to {destination} trip.pdf"
    )
    os.makedirs(
        "backend/pdfs",
        exist_ok=True,
    )
    

    if os.path.exists(filename):

        os.remove(filename)
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # ------------------------------------------------------------------
    # Title
    # ------------------------------------------------------------------

    elements.append(
        Paragraph(
            "TravelSync Trip Summary",
            styles["Title"],
        )
    )
    elements.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"],
        )
    )

    elements.append(Spacer(1, 15))
    elements.append(
        Paragraph(
            "Trip Highlights",
            styles["Heading2"],
        )
    )
    elements.append(
    Paragraph(
        f"A {trip['days']}-day trip from "
        f"{trip['source']} to "
        f"{trip['destination']}.",
        styles["Normal"],
    )
)

    elements.append(
        Spacer(
            1,
            10,
        )
    )
    highlights = [
        f"{trip['source']} → {trip['destination']}",
        f"{trip['travel_mode']}",
        f" {trip['days']} days",
        f" {trip['route']['distance_km']} km",
    ]

    for item in highlights:

        elements.append(
            Paragraph(
                item,
                styles["Normal"],
            )
        )
    elements.append(separator())
    elements.append(Spacer(1, 15))
    # ------------------------------------------------------------------
    # Trip information
    # ------------------------------------------------------------------

    elements.append(
        Paragraph(
            "Trip Information",
            styles["Heading2"],
        )
    )

    trip_data = [
        ["Source", trip["source"]],
        ["Destination", trip["destination"]],
        ["Days", str(trip["days"])],
        ["Travel Mode", trip["travel_mode"]],
        ["Distance", f"{trip['route']['distance_km']} km"],
    ]

    trip_table = Table(
        trip_data,
        colWidths=[120, 300],
    )

    trip_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ]
        )
    )

    elements.append(trip_table)

    elements.append(Spacer(1, 15))
    elements.append(separator())
    # ------------------------------------------------------------------
    # Budget summary
    # ------------------------------------------------------------------

    budget = trip["budget"]

    elements.append(
        Paragraph(
            "Budget Summary",
            styles["Heading2"],
        )
    )

    budget_data = [
        ["Total Budget", f"Rs. {budget['total_budget']}"],
        ["Estimated Cost", f"Rs. {budget['estimated_cost']}"],
        ["Remaining", f"Rs. {budget['remaining']}"],
        ["Status", budget["status"]],
    ]

    budget_table = Table(
        budget_data,
        colWidths=[150, 270],
    )

    budget_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ]
        )
    )
    elements.append(
    Paragraph(
        "Budget Distribution",
        styles["Heading2"],
    )
)

    categories = trip["budget"]["categories"]

    drawing = Drawing(
        400,
        200,
    )

    pie = Pie()

    pie.x = 100
    pie.y = 20

    pie.width = 150
    pie.height = 150

    pie.data = list(
    categories.values()
    )

    pie.labels = list(
        categories.keys()
    )

    drawing.add(pie)

    elements.append(drawing)

    elements.append(
        Spacer(
            1,
            15,
        )
    )

    elements.append(budget_table)
    elements.append(separator())
    elements.append(Spacer(1, 15))

    # ------------------------------------------------------------------
    # Travelers
    # ------------------------------------------------------------------

    elements.append(
        Paragraph(
            "Travelers",
            styles["Heading2"],
        )
    )

    traveler_data = [["Name", "Budget"]]

    for traveler in trip["travelers"]:

        traveler_data.append(
            [
                traveler["name"],
                traveler["budget"],
            ]
        )

    traveler_table = Table(
        traveler_data,
        colWidths=[200, 200],
    )

    traveler_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ]
        )
    )

    elements.append(traveler_table)
    elements.append(separator())
    elements.append(Spacer(1, 15))
    elements.append(
    Paragraph(
        "Travel Statistics",
        styles["Heading2"],
    )
)

    stats = [
        f"Distance: {trip['route']['distance_km']} km",
        f"Travelers: {len(trip['travelers'])}",
        f"Hotels considered: {len(trip['hotels'])}",
        f"Places scheduled: {len(trip['places'])}",
    ]

    for stat in stats:

        elements.append(
            Paragraph(
                stat,
                styles["Normal"],
            )
        )
    # ------------------------------------------------------------------
    # Budget categories
    # ------------------------------------------------------------------

    elements.append(
        Paragraph(
            "Budget Categories",
            styles["Heading2"],
        )
    )

    category_data = [["Category", "Amount"]]

    for category, amount in budget["categories"].items():

        category_data.append(
            [
                category.capitalize(),
                f"Rs. {amount}",
            ]
        )

    category_table = Table(
        category_data,
        colWidths=[200, 200],
    )

    category_table.setStyle(
        TableStyle(
            [
               ("GRID", (0, 0), (-1, -1), 1, colors.black),
("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(
    Paragraph(
        "Emergency Budget",
        styles["Heading2"],
    )
)

    elements.append(
        Paragraph(
            f"Reserved amount: "
            f"Rs. {trip['budget']['categories']['emergency']}",
            styles["Normal"],
    )
)

    elements.append(
        Spacer(
            1,
            10,
        )
    )
    elements.append(category_table)
    elements.append(separator())
    elements.append(Spacer(1, 15))

    # ------------------------------------------------------------------
    # Weather
    # ------------------------------------------------------------------

    if trip["weather"]:

        elements.append(
            Paragraph(
                "Weather Forecast",
                styles["Heading2"],
            )
        )

        weather_data = [["Date", "Temperature"]]

        for day in trip["weather"]:

            weather_data.append(
                [
                    day["date"],
                    f"{day['min_temp']}°C - {day['max_temp']}°C",
                ]
            )

        weather_table = Table(
            weather_data,
            colWidths=[180, 220],
        )

        weather_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ]
            )
        )

        elements.append(weather_table)
        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ------------------------------------------------------------------
    # Hotels
    # ------------------------------------------------------------------

    if trip["hotels"]:

        elements.append(
            Paragraph(
                "Recommended Hotels",
                styles["Heading2"],
            )
        )

        elements.append(
            Paragraph(
            "Recommended Hotels",
            styles["Heading2"],
            )
        )

        hotel_data = [
            [
                "Hotel",
                "Price",
            ]
        ]

        for hotel in trip["hotels"][:5]:

            price = hotel.get(
                "price",
                "N/A",
            )

            hotel_data.append(
                [
                    hotel["name"],
                    str(price),
                ]
            )

        hotel_table = Table(
        hotel_data,
            colWidths=[
                300,
                120,
            ],
        )

        hotel_table.setStyle(
        TableStyle(
            [
                (
                "GRID",
                (0, 0),
                (-1, -1),
                1,
                colors.black,
            ),
            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.lightgrey,
             ),
            ]
        )
    )

    elements.append(
    hotel_table,
)

    elements.append(
        Spacer(
            1,
            15,
        )
    )
    elements.append(separator())
    elements.append(Spacer(1, 15))

    # ------------------------------------------------------------------
    # Daily itinerary
    # ------------------------------------------------------------------

    elements.append(
        Paragraph(
            "Daily Itinerary",
            styles["Heading2"],
        )
    )
    elements.append(
    Paragraph(
        "Trip Overview",
        styles["Heading2"],
    )
)

    overview = (
        f"{trip['days']} days from "
        f"{trip['source']} to "
        f"{trip['destination']} by "
        f"{trip['travel_mode']}."
    )
    elements.append(
        Paragraph(
            overview,
            styles["Normal"],
        )
    )

    for day, places in trip["day_schedule"].items():

        elements.append(
            Paragraph(
                day,
                styles["Heading3"],
            )
        )

        for place in places:
            text = f"<b>{place['name']}</b>"

            if "category" in place:
                text += f" ({place['category']})"

            if place.get("travel_from_previous_km") is not None:
                distance = place["travel_from_previous_km"]

                speeds = {
                    "car": 35,
                    "bus": 25,
                    "train": 40,
                    "flight": 500,
                }

                mode = trip.get("travel_mode", "car").lower()
                speed = speeds.get(mode, 30)

                minutes = max(1, round((distance / speed) * 60))

                text += (
                    f" — {distance:.1f} km"
                    f" • ~{minutes} min"
                    " from previous stop"
                )

            elements.append(
                Paragraph(
                    text,
                    styles["Normal"],
                )
            )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            f"Trip ID: {trip.get('trip_id', 'N/A')}",
            styles["Normal"],
        )
    )

    elements.append(
        Paragraph(
            "Thank you for using TravelSync AI.",
            styles["Heading2"],
        )
    )

    doc.build(
        elements,
        onFirstPage=add_footer,
        onLaterPages=add_footer,
    )

    return filename
   