import os
import re
from datetime import datetime

from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ----------------------------------------------------------------------
# Register Unicode fonts (with graceful fallbacks)
# ----------------------------------------------------------------------
UNICODE_FONT = "Helvetica"
UNICODE_FONT_BOLD = "Helvetica-Bold"

for name, path in [
    ("AppUnicode", "C:/Windows/Fonts/arial.ttf"),
    ("AppUnicode-Bold", "C:/Windows/Fonts/arialbd.ttf"),
    ("AppUnicode", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
    ("AppUnicode-Bold", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
]:
    if os.path.exists(path):
        try:
            pdfmetrics.registerFont(TTFont(name, path))
            if "Bold" in name:
                UNICODE_FONT_BOLD = name
            else:
                UNICODE_FONT = name
        except Exception:
            pass

ARROW_SYM = "->"


def clean_filename(value: str) -> str:
    return re.sub(r'[<>:"/\\\\|?\*]', '', value)


def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont(UNICODE_FONT, 9)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(
        50,
        25,
        f"Generated by TravelSync AI - {datetime.now().strftime('%d-%m-%Y %H:%M')}",
    )
    page_num = canvas.getPageNumber()
    canvas.drawRightString(
        200 * mm,
        25,
        f"Page {page_num}",
    )
    canvas.restoreState()


def generate_pdf(trip: dict) -> str:
    source = trip.get("source", "Source").split(",")[0].strip()
    destination = trip.get("destination", "Destination").split(",")[0].strip()

    safe_source = clean_filename(source)
    safe_destination = clean_filename(destination)

    pdf_dir = "backend/pdfs"
    os.makedirs(pdf_dir, exist_ok=True)

    filename = os.path.join(pdf_dir, f"{safe_source} to {safe_destination} trip.pdf")

    if os.path.exists(filename):
        try:
            os.remove(filename)
        except OSError:
            pass

    doc = SimpleDocTemplate(
        filename,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    doc.title = "TravelSync AI Trip Itinerary"
    doc.author = "TravelSync AI"
    doc.subject = f"Trip from {source} to {destination}"

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "PDFTitle",
        parent=styles["Title"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#1E1B4B"),
    )
    h1_style = ParagraphStyle(
        "PDFH1",
        parent=styles["Heading1"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=17,
        leading=21,
        textColor=colors.HexColor("#312E81"),
    )
    h2_style = ParagraphStyle(
        "PDFH2",
        parent=styles["Heading2"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#1E293B"),
    )
    body_style = ParagraphStyle(
        "PDFBody",
        parent=styles["Normal"],
        fontName=UNICODE_FONT,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155"),
    )
    table_cell_style = ParagraphStyle(
        "PDFTableCell",
        parent=styles["Normal"],
        fontName=UNICODE_FONT,
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
    )
    table_cell_center = ParagraphStyle(
        "PDFTableCellCenter",
        parent=table_cell_style,
        alignment=1,
    )
    table_header_style = ParagraphStyle(
        "PDFTableHeader",
        parent=styles["Normal"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=9,
        leading=12,
        textColor=colors.white,
    )
    table_header_center = ParagraphStyle(
        "PDFTableHeaderCenter",
        parent=table_header_style,
        alignment=1,
    )

    cover_brand_tag = ParagraphStyle(
        "PDFCoverBrandTag",
        parent=styles["Normal"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#4F46E5"),
    )
    cover_meta_line = ParagraphStyle(
        "PDFCoverMetaLine",
        parent=styles["Normal"],
        fontName=UNICODE_FONT,
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#475569"),
    )
    cover_section_heading = ParagraphStyle(
        "PDFCoverSectionHeading",
        parent=styles["Heading2"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#1E293B"),
    )
    cover_cell_label = ParagraphStyle(
        "PDFCoverCellLabel",
        parent=styles["Normal"],
        fontName=UNICODE_FONT,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
    )
    cover_report_meta = ParagraphStyle(
        "PDFCoverReportMeta",
        parent=styles["Normal"],
        fontName=UNICODE_FONT,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
    )
    cover_closing_line = ParagraphStyle(
        "PDFCoverClosingLine",
        parent=styles["Normal"],
        fontName=UNICODE_FONT,
        fontSize=7.8,
        leading=11,
        textColor=colors.HexColor("#94A3B8"),
        alignment=1,
    )

    elements = []
    route_dist = trip.get("route", {}).get("distance_km", "N/A")
    total_scheduled_places = sum(len(p) for p in trip.get("day_schedule", {}).values())
    travelers = trip.get("travelers", [])
    travelers_cnt = len(travelers)
    days_cnt = trip.get("days", 1)

    # ==================================================================
    # 1. Cover Page
    # ==================================================================
    elements.append(Spacer(1, 20))

    # --- A. Title and Route ---
    elements.append(Paragraph("TRAVELSYNC AI &bull; TRAVEL ITINERARY DOSSIER", cover_brand_tag))
    elements.append(Spacer(1, 4))

    custom_title = trip.get("title")
    title_text = custom_title if custom_title else f"Curated Itinerary: {source} to {destination}"
    title_font_size = 11 if len(title_text) > 60 else 12.5
    title_leading = 14 if len(title_text) > 60 else 16
    cover_title_style = ParagraphStyle(
        "PDFCoverTitle",
        parent=styles["Heading2"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=title_font_size,
        leading=title_leading,
        textColor=colors.HexColor("#475569"),
    )
    elements.append(Paragraph(title_text, cover_title_style))
    elements.append(Spacer(1, 7))

    # Primary visual emphasis on route
    route_str = f"{source} {ARROW_SYM} {destination}"
    if len(route_str) > 60:
        route_font_size, route_leading = 17, 21
    elif len(route_str) > 40:
        route_font_size, route_leading = 20, 25
    else:
        route_font_size, route_leading = 24, 29

    cover_route_style = ParagraphStyle(
        "PDFCoverRoute",
        parent=styles["Title"],
        fontName=UNICODE_FONT_BOLD,
        fontSize=route_font_size,
        leading=route_leading,
        textColor=colors.HexColor("#0F172A"),
        alignment=0,
    )
    elements.append(Paragraph(route_str, cover_route_style))
    elements.append(Spacer(1, 6))

    dates_info = trip.get("dates") or trip.get("start_date") or trip.get("travel_dates") or ""
    if trip.get("start_date") and trip.get("end_date") and not trip.get("dates"):
        dates_info = f"{trip['start_date']} &ndash; {trip['end_date']}"
    dates_suffix = f" &bull; {dates_info}" if dates_info else ""
    travel_mode_str = trip.get("travel_mode", "N/A").capitalize()

    elements.append(
        Paragraph(
            f"{days_cnt}-Day Comprehensive Travel Plan{dates_suffix} &bull; {travel_mode_str} Journey",
            cover_meta_line,
        )
    )
    elements.append(Spacer(1, 9))

    accent_bar = Table([[""]], colWidths=[490], rowHeights=[2.5])
    accent_bar.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#4F46E5")),
        ("PADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
    ]))
    elements.append(accent_bar)
    elements.append(Spacer(1, 13))

    # --- B. Trip At A Glance ---
    elements.append(Paragraph("Trip At A Glance", cover_section_heading))
    elements.append(Spacer(1, 5))

    dist_display = f"{route_dist} km" if route_dist != "N/A" else "N/A"
    dist_desc = "Direct & intermediate transit" if route_dist != "N/A" else "Transit distance pending"
    traveler_desc = (
        "Solo traveler dossier"
        if travelers_cnt == 1
        else (f"Coordinated party of {travelers_cnt}" if travelers_cnt > 1 else "Traveler party pending")
    )
    places_desc = f"Curated across {days_cnt} travel day" + ("s" if days_cnt != 1 else "")
    mode_desc = f"Primary travel modality: {travel_mode_str}"

    glance_data = [
        [
            Paragraph(
                f"<font size=7.5 color='#64748B'><b>TRAVEL MODE</b></font><br/>"
                f"<font size=12 color='#0F172A'><b>{travel_mode_str}</b></font><br/>"
                f"<font size=7.2 color='#64748B'>{mode_desc}</font>",
                cover_cell_label,
            ),
            Paragraph(
                f"<font size=7.5 color='#64748B'><b>TRAVELERS</b></font><br/>"
                f"<font size=12 color='#0F172A'><b>{travelers_cnt} Traveler{'s' if travelers_cnt != 1 else ''}</b></font><br/>"
                f"<font size=7.2 color='#64748B'>{traveler_desc}</font>",
                cover_cell_label,
            ),
        ],
        [
            Paragraph(
                f"<font size=7.5 color='#64748B'><b>TOTAL ROUTE DISTANCE</b></font><br/>"
                f"<font size=12 color='#0F172A'><b>{dist_display}</b></font><br/>"
                f"<font size=7.2 color='#64748B'>{dist_desc}</font>",
                cover_cell_label,
            ),
            Paragraph(
                f"<font size=7.5 color='#64748B'><b>SCHEDULED ATTRACTIONS</b></font><br/>"
                f"<font size=12 color='#0F172A'><b>{total_scheduled_places} Places Scheduled</b></font><br/>"
                f"<font size=7.2 color='#64748B'>{places_desc}</font>",
                cover_cell_label,
            ),
        ],
    ]
    glance_table = Table(glance_data, colWidths=[245, 245])
    glance_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(glance_table)
    elements.append(Spacer(1, 13))

    # --- C. Budget Snapshot ---
    elements.append(Paragraph("Budget Snapshot", cover_section_heading))
    elements.append(Spacer(1, 5))

    budget = trip.get("budget", {})
    b_tot = budget.get("total_budget") if budget.get("total_budget") is not None else budget.get("total")
    b_est = budget.get("estimated_cost") if budget.get("estimated_cost") is not None else budget.get("estimated")
    avg_per_person = budget.get("average_per_person")

    if isinstance(b_tot, (int, float)):
        b_tot_str = f"Rs. {b_tot:,.0f}"
        if isinstance(avg_per_person, (int, float)) and avg_per_person > 0:
            avg_traveler_str = f"Rs. {avg_per_person:,.0f}"
        elif travelers_cnt > 0:
            avg_traveler_str = f"Rs. {(b_tot / travelers_cnt):,.0f}"
        else:
            avg_traveler_str = "N/A"
    elif b_tot:
        b_tot_str = str(b_tot)
        avg_traveler_str = "N/A"
    else:
        b_tot_str = "Flexible"
        avg_traveler_str = "N/A"

    if isinstance(b_est, (int, float)):
        b_est_str = f"Rs. {b_est:,.0f}"
    elif b_est:
        b_est_str = str(b_est)
    else:
        b_est_str = "Standard"

    status_note = f"Status: {budget.get('status')}" if budget.get("status") else "Projected expenditure"
    avg_note = f"Per person allocation ({travelers_cnt})" if avg_traveler_str != "N/A" else "Individual breakdown N/A"

    budget_snap_data = [
        [
            Paragraph(
                f"<font size=7.5 color='#4338CA'><b>TOTAL TRIP BUDGET</b></font><br/>"
                f"<font size=12 color='#1E1B4B'><b>{b_tot_str}</b></font><br/>"
                f"<font size=7.2 color='#6366F1'>Allocated overall budget</font>",
                cover_cell_label,
            ),
            Paragraph(
                f"<font size=7.5 color='#4338CA'><b>ESTIMATED EXPENSE</b></font><br/>"
                f"<font size=12 color='#1E1B4B'><b>{b_est_str}</b></font><br/>"
                f"<font size=7.2 color='#6366F1'>{status_note}</font>",
                cover_cell_label,
            ),
            Paragraph(
                f"<font size=7.5 color='#4338CA'><b>AVG PER TRAVELER</b></font><br/>"
                f"<font size=12 color='#1E1B4B'><b>{avg_traveler_str}</b></font><br/>"
                f"<font size=7.2 color='#6366F1'>{avg_note}</font>",
                cover_cell_label,
            ),
        ]
    ]
    budget_snap_table = Table(budget_snap_data, colWidths=[163, 163, 164])
    budget_snap_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EEF2FF")),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#C7D2FE")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E0E7FF")),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(budget_snap_table)
    elements.append(Spacer(1, 13))

    # --- D. Itinerary Highlights (Featured scheduled stops) ---
    elements.append(Paragraph("Itinerary Highlights", cover_section_heading))
    elements.append(Spacer(1, 5))

    day_schedule = trip.get("day_schedule", {})
    highlights = []
    seen_names = set()
    for d_key in sorted(day_schedule.keys(), key=lambda x: int(x) if x.isdigit() else 99):
        pls = day_schedule[d_key]
        if isinstance(pls, list):
            for p in pls:
                p_name = p.get("name")
                if p_name and p_name not in seen_names:
                    seen_names.add(p_name)
                    highlights.append({
                        "day": f"Day {d_key}",
                        "name": p_name,
                        "category": p.get("category") or "Attraction",
                        "best_time": p.get("best_time") or "",
                    })
                    break
        if len(highlights) >= 3:
            break

    if len(highlights) < 3:
        for d_key in sorted(day_schedule.keys(), key=lambda x: int(x) if x.isdigit() else 99):
            pls = day_schedule[d_key]
            if isinstance(pls, list):
                for p in pls:
                    p_name = p.get("name")
                    if p_name and p_name not in seen_names:
                        seen_names.add(p_name)
                        highlights.append({
                            "day": f"Day {d_key}",
                            "name": p_name,
                            "category": p.get("category") or "Attraction",
                            "best_time": p.get("best_time") or "",
                        })
                    if len(highlights) >= 3:
                        break
            if len(highlights) >= 3:
                break

    if highlights:
        hl_rows = [
            [
                Paragraph("<b>Timeline</b>", table_header_style),
                Paragraph("<b>Key Scheduled Attraction</b>", table_header_style),
                Paragraph("<b>Category</b>", table_header_style),
            ]
        ]
        for hl in highlights:
            time_sub = f"<br/><font size=7.2 color='#64748B'>Timing: {hl['best_time']}</font>" if hl.get("best_time") else ""
            hl_rows.append([
                Paragraph(f"<b>{hl['day']}</b><br/><font size=7.2 color='#64748B'>Scheduled Stop</font>", table_cell_style),
                Paragraph(f"<b>{hl['name']}</b>{time_sub}", table_cell_style),
                Paragraph(f"<b>{hl['category']}</b><br/><font size=7.2 color='#64748B'>Curated Attraction</font>", table_cell_style),
            ])
        hl_table = Table(hl_rows, colWidths=[80, 260, 150])
        hl_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#312E81")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("PADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5.5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]))
        elements.append(hl_table)
    else:
        no_hl = Table([[
            Paragraph("<b>Daily Itinerary Plan</b><br/><font size=7.2 color='#64748B'>Schedule Status</font>", table_cell_style),
            Paragraph("Personalized attraction stops scheduled across travel days.<br/><font size=7.2 color='#64748B'>Full daily breakdown provided in following sections.</font>", table_cell_style),
        ]], colWidths=[140, 350])
        no_hl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(no_hl)
    elements.append(Spacer(1, 13))

    # --- E. Report Details & Footer ---
    trip_id_str = str(trip.get("trip_id") or "N/A")
    gen_time = datetime.now().strftime("%d %B %Y, %H:%M")
    meta_data = [
        [
            Paragraph(f"<font size=7.2 color='#64748B'><b>TRIP REFERENCE ID</b></font><br/><b>{trip_id_str}</b>", cover_report_meta),
            Paragraph(f"<font size=7.2 color='#64748B'><b>ISSUED DATE & TIME</b></font><br/><b>{gen_time}</b>", cover_report_meta),
        ],
        [
            Paragraph("<font size=7.2 color='#64748B'><b>DOSSIER STATUS</b></font><br/><b>Confirmed Itinerary Dossier</b>", cover_report_meta),
            Paragraph("<font size=7.2 color='#64748B'><b>PLANNING ENGINE</b></font><br/><b>TravelSync AI Intelligent Itinerary System</b>", cover_report_meta),
        ],
    ]
    meta_table = Table(meta_data, colWidths=[245, 245])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("PADDING", (0, 0), (-1, -1), 5.5),
        ("TOPPADDING", (0, 0), (-1, -1), 5.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 9))

    elements.append(
        Paragraph(
            "This travel dossier was generated by TravelSync AI. Comprehensive daily schedules, route segments, and hotel recommendations begin on page 2.",
            cover_closing_line,
        )
    )

    elements.append(PageBreak())

    # ==================================================================
    # 2. Trip Overview & Highlights
    # ==================================================================
    elements.append(Paragraph("Trip Summary & Highlights", h1_style))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%d-%m-%Y %H:%M')}", body_style))
    elements.append(Spacer(1, 8))

    elements.append(Paragraph(f"- <b>Route:</b> {trip.get('source', '')} {ARROW_SYM} {trip.get('destination', '')}", body_style))
    elements.append(Paragraph(
        f"- <b>Mode:</b> {trip.get('travel_mode', 'N/A').capitalize()} &bull; "
        f"<b>Duration:</b> {trip.get('days', 1)} days &bull; "
        f"<b>Total Distance:</b> {route_dist} km",
        body_style,
    ))
    elements.append(Spacer(1, 10))

    # ==================================================================
    # 3. Budget Summary & Pie Chart with Clear Legend
    # ==================================================================
    budget = trip.get("budget", {})
    if budget:
        elements.append(Paragraph("Budget Summary", h2_style))
        elements.append(Spacer(1, 4))

        b_tot = budget.get("total_budget") if budget.get("total_budget") is not None else budget.get("total", "N/A")
        b_est = budget.get("estimated_cost") if budget.get("estimated_cost") is not None else budget.get("estimated", "N/A")
        b_rem = budget.get("remaining", "N/A")
        tot_str = f"Rs. {b_tot:,}" if isinstance(b_tot, (int, float)) else f"Rs. {b_tot}"
        est_str = f"Rs. {b_est:,}" if isinstance(b_est, (int, float)) else f"Rs. {b_est}"
        rem_str = f"Rs. {b_rem:,}" if isinstance(b_rem, (int, float)) else f"Rs. {b_rem}"

        budget_data = [
            [Paragraph("<b>Metric</b>", table_header_style), Paragraph("<b>Details</b>", table_header_style)],
            [Paragraph("Total Budget", table_cell_style), Paragraph(tot_str, table_cell_style)],
            [Paragraph("Estimated Cost", table_cell_style), Paragraph(est_str, table_cell_style)],
            [Paragraph("Remaining", table_cell_style), Paragraph(rem_str, table_cell_style)],
            [Paragraph("Status", table_cell_style), Paragraph(str(budget.get("status", "N/A")), table_cell_style)],
        ]
        b_table = Table(budget_data, colWidths=[160, 290])
        b_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ]
            )
        )
        elements.append(b_table)
        elements.append(Spacer(1, 10))

        # Budget Allocation Pie Chart with Legend
        categories = budget.get("categories") or budget.get("breakdown") or {}
        preferred_order = ["hotel", "food", "transport", "activities", "emergency"]
        ordered_cats = []
        for c_key in preferred_order:
            val = categories.get(c_key)
            if isinstance(val, (int, float)) and val > 0:
                ordered_cats.append((c_key.capitalize(), float(val)))
        for c_key, val in categories.items():
            if c_key.lower() not in preferred_order and isinstance(val, (int, float)) and val > 0:
                ordered_cats.append((c_key.capitalize(), float(val)))

        if ordered_cats:
            elements.append(Paragraph("Budget Distribution", h2_style))
            elements.append(Spacer(1, 4))
            drawing = Drawing(450, 150)
            pie = Pie()
            pie.x = 15
            pie.y = 10
            pie.width = 130
            pie.height = 130
            pie.data = [v for _, v in ordered_cats]
            pie.labels = []  # Omit overlapping slice labels in favor of legend

            slice_palette = [
                colors.HexColor("#4F46E5"),
                colors.HexColor("#06B6D4"),
                colors.HexColor("#10B981"),
                colors.HexColor("#F59E0B"),
                colors.HexColor("#EF4444"),
                colors.HexColor("#8B5CF6"),
                colors.HexColor("#EC4899"),
            ]
            for i in range(len(ordered_cats)):
                pie.slices[i].fillColor = slice_palette[i % len(slice_palette)]

            legend = Legend()
            legend.x = 180
            legend.y = 135
            legend.dx = 10
            legend.dy = 10
            legend.fontName = UNICODE_FONT
            legend.fontSize = 8.5
            legend.boxAnchor = "nw"
            legend.columnMaximum = 6
            cat_total = sum(v for _, v in ordered_cats) or 1.0
            legend.colorNamePairs = [
                (
                    slice_palette[i % len(slice_palette)],
                    f"{cat}: Rs. {amt:,.0f} ({(amt / cat_total) * 100:.1f}%)"
                )
                for i, (cat, amt) in enumerate(ordered_cats)
            ]
            drawing.add(pie)
            drawing.add(legend)
            elements.append(drawing)
            elements.append(Spacer(1, 8))

        traveler_count = len(trip.get("travelers", []))
        if traveler_count > 0 and isinstance(budget.get("total_budget"), (int, float)):
            per_traveler = budget["total_budget"] / traveler_count
            elements.append(
                Paragraph(
                    f"<b>Average Budget Per Traveler:</b> Rs. {per_traveler:,.2f} (from total trip budget)",
                    body_style,
                )
            )
            elements.append(Spacer(1, 10))

    # ==================================================================
    # 4. Travelers Information
    # ==================================================================
    travelers = trip.get("travelers", [])
    if travelers:
        elements.append(Paragraph("Travelers", h2_style))
        elements.append(Spacer(1, 4))
        traveler_data = [[
            Paragraph("<b>Name</b>", table_header_style),
            Paragraph("<b>Interests</b>", table_header_style),
            Paragraph("<b>Budget Preference</b>", table_header_style),
        ]]
        for t in travelers:
            b_val = t.get("budget", "N/A")
            try:
                b_display = f"Rs. {float(b_val):,.2f}"
            except (ValueError, TypeError):
                b_display = str(b_val).capitalize()
            traveler_data.append([
                Paragraph(t.get("name", "Traveler"), table_cell_style),
                Paragraph(", ".join(t.get("interests", [])) or "All", table_cell_style),
                Paragraph(b_display, table_cell_style),
            ])
        t_table = Table(traveler_data, colWidths=[150, 180, 120])
        t_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ]
            )
        )
        elements.append(t_table)
        elements.append(Spacer(1, 10))

    # ==================================================================
    # 5. Recommended Hotels (3 columns: Hotel | Price | Rating)
    # ==================================================================
    hotels = trip.get("hotels", [])
    if hotels:
        elements.append(Paragraph("Recommended Hotels", h2_style))
        elements.append(Spacer(1, 4))
        hotel_data = [[
            Paragraph("<b>Hotel</b>", table_header_style),
            Paragraph("<b>Price</b>", table_header_style),
            Paragraph("<b>Rating</b>", table_header_center),
        ]]
        for hotel in hotels[:5]:
            p = hotel.get("price") or hotel.get("price_inr") or hotel.get("price_per_night")
            if isinstance(p, (int, float)):
                p_str = f"Rs. {p:,}"
            elif p not in [None, "", "N/A"]:
                p_str = f"Rs. {p}"
            else:
                p_str = "N/A"
            r = hotel.get("rating")
            r_str = f"{r} / 5" if r not in [None, "", "N/A"] else "N/A"
            hotel_data.append([
                Paragraph(hotel.get("name", "Unknown Hotel"), table_cell_style),
                Paragraph(p_str, table_cell_style),
                Paragraph(r_str, table_cell_center),
            ])
        h_table = Table(hotel_data, colWidths=[240, 110, 100], repeatRows=1)
        h_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ]
            )
        )
        elements.append(h_table)
        elements.append(Spacer(1, 10))

    # ==================================================================
    # 6. Weather Forecast
    # ==================================================================
    weather_list = trip.get("weather", [])
    if weather_list:
        elements.append(Paragraph("Weather Forecast", h2_style))
        elements.append(Spacer(1, 4))
        weather_data = [[
            Paragraph("<b>Date / Day</b>", table_header_style),
            Paragraph("<b>Temperature Range</b>", table_header_style),
            Paragraph("<b>Condition</b>", table_header_style),
        ]]
        days_limit = int(trip.get("days", len(weather_list)))
        for dw in weather_list[:days_limit]:
            d_label = str(dw.get("date") or dw.get("day") or "N/A")
            min_t = dw.get("min_temp")
            max_t = dw.get("max_temp")
            temp_c = dw.get("temp_c") if dw.get("temp_c") is not None else dw.get("temp")
            if min_t is not None and max_t is not None:
                t_str = f"{min_t}°C - {max_t}°C"
            elif temp_c is not None:
                t_str = f"{temp_c}°C"
            else:
                t_str = "N/A"
            cond = str(dw.get("condition") or dw.get("weather_code") or "Pleasant")
            weather_data.append([
                Paragraph(d_label, table_cell_style),
                Paragraph(t_str, table_cell_style),
                Paragraph(cond, table_cell_style),
            ])
        w_table = Table(weather_data, colWidths=[150, 150, 150])
        w_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ]
            )
        )
        elements.append(w_table)
        elements.append(Spacer(1, 10))

    # ==================================================================
    # 7. Daily Itinerary (Starts on a fresh page)
    # ==================================================================
    elements.append(CondPageBreak(350))

    elements.append(Paragraph("Daily Itinerary", h1_style))
    elements.append(
        Paragraph(
            f"{trip.get('days', 1)} days from {trip.get('source', '')} {ARROW_SYM} "
            f"{trip.get('destination', '')} by {trip.get('travel_mode', 'car').capitalize()}.",
            body_style,
        )
    )
    elements.append(Spacer(1, 8))

    day_schedule = trip.get("day_schedule", {})
    speeds = {"car": 35, "bus": 25, "train": 40, "flight": 500}
    mode = trip.get("travel_mode", "car").lower()
    speed = speeds.get(mode, 30)

    for day_label, places in day_schedule.items():
        day_title = f"Day {day_label}" if str(day_label).isdigit() else str(day_label)
        elements.append(Paragraph(day_title, h2_style))
        elements.append(Spacer(1, 4))

        day_table_data = [[
            Paragraph("<b>Place</b>", table_header_style),
            Paragraph("<b>Category</b>", table_header_style),
            Paragraph("<b>Travel Distance</b>", table_header_center),
        ]]

        for idx, place in enumerate(places):
            dist = place.get("travel_from_previous_km")
            if idx == 0:
                dist_str = "Day Start"
            elif dist is not None and dist > 0:
                dist_str = f"{dist:.1f} km"
            else:
                dist_str = "N/A"

            day_table_data.append([
                Paragraph(f"<b>{place.get('name', 'Unknown')}</b>", table_cell_style),
                Paragraph(place.get("category", "N/A"), table_cell_style),
                Paragraph(dist_str, table_cell_center),
            ])

        day_table = Table(day_table_data, colWidths=[230, 130, 90], repeatRows=1)
        day_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("PADDING", (0, 0), (-1, -1), 5),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ]
            )
        )
        elements.append(day_table)
        elements.append(Spacer(1, 6))

        # Attraction explanations and travel distance/time
        for idx, place in enumerate(places):
            p_text = f"<b>{place.get('name', 'Unknown')}</b>"
            if "category" in place and place["category"]:
                p_text += f" ({place['category']})"

            expl = place.get("explanation")
            if expl and expl != "Unable to generate an explanation.":
                p_text += f"<br/><font size='8' color='#475569'>{expl}</font>"
            else:
                p_text += "<br/><font size='8' color='#94A3B8'>Explanation unavailable.</font>"

            if idx == 0:
                p_text += "<br/><font size='8' color='#64748B'>&bull; First stop of the day</font>"
            elif place.get("travel_from_previous_km") is not None and place.get("travel_from_previous_km") > 0:
                p_dist = place["travel_from_previous_km"]
                mins = max(1, round((p_dist / speed) * 60))
                p_text += (
                    f"<br/><font size='8' color='#64748B'>&bull; {p_dist:.1f} km &bull; ~{mins} min {mode.capitalize()} from previous stop</font>"
                )
            else:
                p_text += "<br/><font size='8' color='#64748B'>&bull; Distance from previous stop: N/A</font>"

            elements.append(Paragraph(p_text, body_style))
            elements.append(Spacer(1, 4))

        elements.append(Spacer(1, 8))

    # ==================================================================
    # 8. Trip Notes (Rendered once, only if present)
    # ==================================================================
    raw_notes = trip.get("notes") or []
    valid_notes = [str(n).strip() for n in raw_notes if n and str(n).strip()]
    if valid_notes:
        elements.append(Paragraph("Trip Notes", h2_style))
        elements.append(Spacer(1, 4))
        for note in valid_notes:
            elements.append(Paragraph(f"&bull; {note}", body_style))
            elements.append(Spacer(1, 3))
        elements.append(Spacer(1, 8))

    # ==================================================================
    # 9. Final Trip Summary (Kept together, no trailing blank page)
    # ==================================================================
    summary_data = [
        [Paragraph("<b>Metric</b>", table_header_style), Paragraph("<b>Value</b>", table_header_style)],
        [Paragraph("Duration", table_cell_style), Paragraph(f"{trip.get('days', 1)} days", table_cell_style)],
        [Paragraph("Travelers", table_cell_style), Paragraph(str(len(travelers)), table_cell_style)],
        [Paragraph("Places Scheduled", table_cell_style), Paragraph(str(total_scheduled_places), table_cell_style)],
        [Paragraph("Total Distance", table_cell_style), Paragraph(f"{route_dist} km", table_cell_style)],
        [Paragraph("Estimated Cost", table_cell_style), Paragraph(est_str if budget else "N/A", table_cell_style)],
        [Paragraph("Budget Status", table_cell_style), Paragraph(str(budget.get("status", "N/A")), table_cell_style)],
    ]
    sum_table = Table(summary_data, colWidths=[180, 270])
    sum_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("PADDING", (0, 0), (-1, -1), 5),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ]
        )
    )

    numeric_traveler_budgets = []
    for traveler in travelers:
        val = traveler.get("budget", 0)
        try:
            numeric_traveler_budgets.append(float(val))
        except (TypeError, ValueError):
            continue

    if numeric_traveler_budgets:
        traveler_budget_text = f"Rs. {sum(numeric_traveler_budgets):,.2f}"
    else:
        traveler_budget_text = f"Allocated from trip total ({tot_str})" if budget else "Not specified"

    elements.append(
        KeepTogether(
            [
                Paragraph("Final Trip Summary", h2_style),
                Spacer(1, 4),
                sum_table,
                Spacer(1, 6),
                Paragraph(f"<b>Total Traveler Budget:</b> {traveler_budget_text}", body_style),
                Spacer(1, 6),
                Paragraph("Thank you for using TravelSync AI.", h2_style),
            ]
        )
    )

    # Build document
    doc.build(
        elements,
        onFirstPage=add_footer,
        onLaterPages=add_footer,
    )

    return filename
