import os
import re
from datetime import datetime

from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def clean_filename(value: str) -> str:
    return re.sub(r'[<>:"/\\\\|?\*]', '', value)


def separator():
    return HRFlowable(
        width="100%",
        thickness=1,
        color=colors.HexColor("#CCCCCC"),
    )


def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#666666"))
    canvas.drawString(
        50,
        30,
        f"Generated by TravelSync AI • {datetime.now().strftime('%d-%m-%Y %H:%M')}",
    )
    page_num = canvas.getPageNumber()
    canvas.drawRightString(
        200 * mm,
        30,
        f"Page {page_num}",
    )
    canvas.restoreState()


def generate_pdf(trip: dict) -> str:
    source = trip.get("source", "Source").split(",")[0].strip()
    destination = trip.get("destination", "Destination").split(",")[0].strip()

    safe_source = clean_filename(source)
    safe_destination = clean_filename(destination)

    pdf_dir = "backend/pdfs"
    os.makedirs(pdf_dir, exist_ok=True)

    filename = os.path.join(pdf_dir, f"{safe_source} to {safe_destination} trip.pdf")

    if os.path.exists(filename):
        try:
            os.remove(filename)
        except OSError:
            pass

    doc = SimpleDocTemplate(
        filename,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )
    doc.title = "TravelSync AI Trip Itinerary"
    doc.author = "TravelSync AI"
    doc.subject = f"Trip from {source} to {destination}"

    styles = getSampleStyleSheet()
    elements = []

    # ==================================================================
    # 1. Cover Page
    # ==================================================================
    elements.append(Spacer(1, 80))
    elements.append(Paragraph("TravelSync AI", styles["Title"]))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(f"{source} &rarr; {destination}", styles["Heading1"]))
    elements.append(Spacer(1, 15))
    elements.append(Paragraph(f"{trip.get('days', 1)}-Day Trip", styles["Heading2"]))
    elements.append(Spacer(1, 20))
    elements.append(
        Paragraph(
            f"Travel Mode: {trip.get('travel_mode', 'N/A').capitalize()}",
            styles["Normal"],
        )
    )
    elements.append(
        Paragraph(
            f"Travelers: {len(trip.get('travelers', []))}",
            styles["Normal"],
        )
    )
    route_dist = trip.get("route", {}).get("distance_km", "N/A")
    elements.append(
        Paragraph(
            f"Total Distance: {route_dist} km",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 40))
    elements.append(
        Paragraph(
            f"Trip ID: {trip.get('trip_id', 'N/A')}",
            styles["Normal"],
        )
    )

    # End of cover page
    elements.append(PageBreak())

    # ==================================================================
    # 2. Trip Overview & Highlights
    # ==================================================================
    elements.append(Paragraph("TravelSync Trip Summary", styles["Title"]))
    elements.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 15))

    elements.append(Paragraph("Trip Highlights", styles["Heading2"]))
    elements.append(
        Paragraph(
            f"A {trip.get('days', 1)}-day trip from {trip.get('source', '')} to {trip.get('destination', '')}.",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 10))

    highlights = [
        f"• Route: {trip.get('source', '')} &rarr; {trip.get('destination', '')}",
        f"• Mode: {trip.get('travel_mode', 'N/A').capitalize()}",
        f"• Duration: {trip.get('days', 1)} days",
        f"• Total Distance: {route_dist} km",
    ]
    for item in highlights:
        elements.append(Paragraph(item, styles["Normal"]))

    elements.append(Spacer(1, 15))
    elements.append(separator())
    elements.append(Spacer(1, 15))

    # ==================================================================
    # 3. Trip Information Table
    # ==================================================================
    elements.append(Paragraph("Trip Information", styles["Heading2"]))
    trip_data = [
        ["Source", trip.get("source", "N/A")],
        ["Destination", trip.get("destination", "N/A")],
        ["Duration", f"{trip.get('days', 1)} days"],
        ["Travel Mode", trip.get("travel_mode", "N/A").capitalize()],
        ["Distance", f"{route_dist} km"],
        ["Travelers", str(len(trip.get("travelers", [])))],
    ]
    trip_table = Table(trip_data, colWidths=[120, 300])
    trip_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(trip_table)
    elements.append(Spacer(1, 15))
    elements.append(separator())
    elements.append(Spacer(1, 15))

    # ==================================================================
    # 4. Budget Summary & Distribution
    # ==================================================================
    budget = trip.get("budget", {})
    if budget:
        elements.append(Paragraph("Budget Summary", styles["Heading2"]))
        budget_data = [
            ["Total Budget", f"Rs. {budget.get('total_budget', 'N/A')}"],
            ["Estimated Cost", f"Rs. {budget.get('estimated_cost', 'N/A')}"],
            ["Remaining", f"Rs. {budget.get('remaining', 'N/A')}"],
            ["Status", str(budget.get("status", "N/A"))],
        ]
        budget_table = Table(budget_data, colWidths=[150, 270])
        budget_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(budget_table)
        elements.append(Spacer(1, 15))

        categories = budget.get("categories", {})
        if categories and any(isinstance(v, (int, float)) and v > 0 for v in categories.values()):
            elements.append(Paragraph("Budget Distribution", styles["Heading2"]))
            drawing = Drawing(400, 200)
            pie = Pie()
            pie.x = 100
            pie.y = 20
            pie.width = 150
            pie.height = 150
            pie.data = [float(v) for v in categories.values() if isinstance(v, (int, float))]
            pie.labels = [str(k).capitalize() for k, v in categories.items() if isinstance(v, (int, float))]
            drawing.add(pie)
            elements.append(drawing)
            elements.append(Spacer(1, 15))

        traveler_count = len(trip.get("travelers", []))
        if traveler_count > 0 and isinstance(budget.get("total_budget"), (int, float)):
            per_traveler = budget["total_budget"] / traveler_count
            elements.append(
                Paragraph(
                    f"Average Budget Per Traveler: Rs. {per_traveler:.2f}",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 10))

        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ==================================================================
    # 5. Travelers Information
    # ==================================================================
    travelers = trip.get("travelers", [])
    if travelers:
        elements.append(Paragraph("Travelers", styles["Heading2"]))
        traveler_data = [["Name", "Budget"]]
        for traveler in travelers:
            traveler_data.append([
                traveler.get("name", "Traveler"),
                str(traveler.get("budget", "N/A")),
            ])
        traveler_table = Table(traveler_data, colWidths=[200, 200])
        traveler_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(traveler_table)
        elements.append(Spacer(1, 15))
        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ==================================================================
    # 6. Travel Statistics
    # ==================================================================
    elements.append(Paragraph("Travel Statistics", styles["Heading2"]))
    stats = [
        f"• Total Distance: {route_dist} km",
        f"• Number of Travelers: {len(travelers)}",
        f"• Hotels Considered: {len(trip.get('hotels', []))}",
        f"• Places Scheduled: {len(trip.get('places', []))}",
    ]
    for stat in stats:
        elements.append(Paragraph(stat, styles["Normal"]))
    elements.append(Spacer(1, 15))

    # ==================================================================
    # 7. Budget Categories Breakdown & Emergency Budget
    # ==================================================================
    if budget and budget.get("categories"):
        elements.append(Paragraph("Budget Categories", styles["Heading2"]))
        category_data = [["Category", "Amount"]]
        for category, amount in budget["categories"].items():
            category_data.append([
                category.capitalize(),
                f"Rs. {amount}",
            ])
        category_table = Table(category_data, colWidths=[200, 200])
        category_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(category_table)
        elements.append(Spacer(1, 10))

        emergency_val = budget["categories"].get("emergency", 0)
        elements.append(Paragraph("Emergency Budget", styles["Heading2"]))
        elements.append(
            Paragraph(
                f"Reserved amount: Rs. {emergency_val}",
                styles["Normal"],
            )
        )
        elements.append(Spacer(1, 15))
        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ==================================================================
    # 8. Weather Forecast
    # ==================================================================
    weather_list = trip.get("weather", [])
    if weather_list:
        elements.append(Paragraph("Weather Forecast", styles["Heading2"]))
        weather_data = [["Date", "Temperature"]]
        days_limit = int(trip.get("days", len(weather_list)))
        for day_weather in weather_list[:days_limit]:
            weather_data.append([
                str(day_weather.get("date", "N/A")),
                f"{day_weather.get('min_temp', 'N/A')}°C - {day_weather.get('max_temp', 'N/A')}°C",
            ])
        weather_table = Table(weather_data, colWidths=[180, 220])
        weather_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(weather_table)
        elements.append(Spacer(1, 15))
        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ==================================================================
    # 9. Recommended Hotels (Correct hotel_data and 3-column headers)
    # ==================================================================
    hotels = trip.get("hotels", [])
    if hotels:
        elements.append(Paragraph("Recommended Hotels", styles["Heading2"]))
        hotel_data = [["Hotel", "Price", "Rating"]]
        for hotel in hotels[:5]:
            price = hotel.get("price", "N/A")
            rating = hotel.get("rating", "N/A")
            hotel_data.append([
                hotel.get("name", "Unknown Hotel"),
                str(price),
                str(rating),
            ])
        hotel_table = Table(hotel_data, colWidths=[250, 100, 100])
        hotel_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(hotel_table)
        elements.append(Spacer(1, 15))
        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ==================================================================
    # 10. Daily Itinerary (Starts on a new page)
    # ==================================================================
    elements.append(PageBreak())

    elements.append(Paragraph("Daily Itinerary", styles["Heading1"]))
    overview_text = (
        f"{trip.get('days', 1)} days from {trip.get('source', '')} to "
        f"{trip.get('destination', '')} by {trip.get('travel_mode', 'car')}."
    )
    elements.append(Paragraph(overview_text, styles["Normal"]))
    elements.append(Spacer(1, 10))

    day_schedule = trip.get("day_schedule", {})
    speeds = {
        "car": 35,
        "bus": 25,
        "train": 40,
        "flight": 500,
    }
    mode = trip.get("travel_mode", "car").lower()
    speed = speeds.get(mode, 30)

    for day_label, places in day_schedule.items():
        elements.append(Paragraph(day_label, styles["Heading3"]))
        day_table_data = [["Place", "Category", "Distance"]]

        for place in places:
            dist = place.get("travel_from_previous_km")
            dist_str = f"{dist:.1f} km" if dist is not None else "N/A"
            day_table_data.append([
                place.get("name", "Unknown"),
                place.get("category", "N/A"),
                dist_str,
            ])

        day_table = Table(day_table_data, colWidths=[240, 120, 100])
        day_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("PADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(day_table)
        elements.append(Spacer(1, 8))

        # Day weather
        try:
            day_num = int(day_label.split()[-1])
        except (ValueError, IndexError):
            day_num = 1

        if weather_list and day_num <= len(weather_list):
            dw = weather_list[day_num - 1]
            elements.append(
                Paragraph(
                    f"Weather: {dw.get('min_temp', 'N/A')}°C - {dw.get('max_temp', 'N/A')}°C",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 6))

        # Attraction explanations and travel distance/time
        for place in places:
            p_text = f"<b>{place.get('name', 'Unknown')}</b>"
            if place.get("explanation"):
                p_text += f"<br/><font size='9' color='grey'>{place['explanation']}</font>"
            if "category" in place:
                p_text += f" ({place['category']})"

            if place.get("travel_from_previous_km") is not None:
                p_dist = place["travel_from_previous_km"]
                mins = max(1, round((p_dist / speed) * 60))
                p_text += (
                    f" &mdash; {p_dist:.1f} km"
                    f" &bull; ~{mins} min"
                    f" &bull; {mode.capitalize()} from previous stop"
                )

            elements.append(Paragraph(p_text, styles["Normal"]))
            elements.append(Spacer(1, 4))

        elements.append(Spacer(1, 10))

    elements.append(Spacer(1, 15))
    elements.append(
        Paragraph(
            f"Trip ID: {trip.get('trip_id', 'N/A')}",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 10))

    # ==================================================================
    # 11. Trip Notes (Single section, no duplicates)
    # ==================================================================
    notes = trip.get("notes", [])
    if notes:
        elements.append(Paragraph("Trip Notes", styles["Heading2"]))
        for note in notes:
            elements.append(Paragraph(f"&bull; {note}", styles["Normal"]))
            elements.append(Spacer(1, 4))
        elements.append(Spacer(1, 10))
        elements.append(separator())
        elements.append(Spacer(1, 15))

    # ==================================================================
    # 12. Final Trip Summary
    # ==================================================================
    elements.append(Paragraph("Trip Summary", styles["Heading2"]))
    summary_data = [
        ["Metric", "Value"],
        ["Duration", f"{trip.get('days', 1)} days"],
        ["Travelers", str(len(travelers))],
        ["Total Distance", f"{route_dist} km"],
        ["Estimated Cost", f"Rs. {budget.get('estimated_cost', 'N/A')}"],
        ["Budget Status", str(budget.get("status", "N/A"))],
    ]
    summary_table = Table(summary_data, colWidths=[200, 200])
    summary_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(summary_table)
    elements.append(Spacer(1, 10))

    numeric_traveler_budgets = []
    for traveler in travelers:
        val = traveler.get("budget", 0)
        try:
            numeric_traveler_budgets.append(float(val))
        except (TypeError, ValueError):
            continue

    if numeric_traveler_budgets:
        traveler_budget_text = f"Rs. {sum(numeric_traveler_budgets):.2f}"
    else:
        traveler_budget_text = "Not specified as a numeric amount"

    elements.append(
        Paragraph(
            f"Total Traveler Budget: {traveler_budget_text}",
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 15))
    elements.append(
        Paragraph(
            "Thank you for using TravelSync AI.",
            styles["Heading2"],
        )
    )

    doc.build(
        elements,
        onFirstPage=add_footer,
        onLaterPages=add_footer,
    )

    return filename
